∑¢ÀÕ ß∞‹£∫
Traceback (most recent call last):
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\spider_logging\kafka_handler.py", line 147, in emit
    self.producer.send(self.topic, value=msg, key=self.key)
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\kafka\producer\kafka.py", line 600, in send
    result = self._accumulator.append(tp, timestamp_ms,
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\kafka\producer\record_accumulator.py", line 221, in append
    assert not self._closed, 'RecordAccumulator is closed'
AssertionError: RecordAccumulator is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\spider_logging\kafka_handler.py", line 151, in emit
    self.send_to_bak_kafka(msg)
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\spider_logging\kafka_handler.py", line 328, in send_to_bak_kafka
    raise RuntimeError('send log failed')
RuntimeError: send log failed

∑¢ÀÕ ß∞‹£∫
Traceback (most recent call last):
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\spider_logging\kafka_handler.py", line 147, in emit
    self.producer.send(self.topic, value=msg, key=self.key)
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\kafka\producer\kafka.py", line 600, in send
    result = self._accumulator.append(tp, timestamp_ms,
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\kafka\producer\record_accumulator.py", line 221, in append
    assert not self._closed, 'RecordAccumulator is closed'
AssertionError: RecordAccumulator is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\spider_logging\kafka_handler.py", line 151, in emit
    self.send_to_bak_kafka(msg)
  File "E:\work\fmj\Code_Workspace\PythonVirtualEnv\NAV_SPIDER_ENV\lib\site-packages\spider_logging\kafka_handler.py", line 328, in send_to_bak_kafka
    raise RuntimeError('send log failed')
RuntimeError: send log failed

